-- create cats table
CREATE TABLE cats (
                      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

                      name VARCHAR(255) NOT NULL,

                      breed VARCHAR(255) NOT NULL,

                      years_of_experience INTEGER NOT NULL CHECK (years_of_experience >= 0),

                      salary DECIMAL(10, 2) NOT NULL CHECK (salary >= 0),

                      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- comments
COMMENT ON TABLE cats IS 'Stores information about the spy cats of the agency.';
COMMENT ON COLUMN cats.id IS 'Unique identifier for each cat (UUID).';
COMMENT ON COLUMN cats.name IS 'The given name of the spy cat.';
COMMENT ON COLUMN cats.breed IS 'The breed of the cat (e.g., Siamese, Persian).';
COMMENT ON COLUMN cats.years_of_experience IS 'Total years of spying experience.';
COMMENT ON COLUMN cats.salary IS 'The annual salary of the cat.';
COMMENT ON COLUMN cats.created_at IS 'The timestamp when the cat was added to the system.';