CREATE TABLE missions (
                          id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

                          cat_id INTEGER REFERENCES cats(id) ON DELETE SET NULL,

                          complete BOOLEAN NOT NULL DEFAULT FALSE,

                          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX missions_unique_active_cat_id_idx ON missions (cat_id) WHERE (complete = FALSE);

COMMENT ON TABLE missions IS 'Stores overarching mission data and its assignment to a cat.';
COMMENT ON COLUMN missions.cat_id IS 'The cat assigned to this mission. NULL if unassigned.';
COMMENT ON COLUMN missions.complete IS 'True if the mission and all its targets are complete.';
COMMENT ON INDEX missions_unique_active_cat_id_idx IS 'Ensures a cat is only assigned to one incomplete mission at a time.';