CREATE TABLE targets (
                         id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

                         mission_id INTEGER NOT NULL REFERENCES missions(id) ON DELETE CASCADE,

                         name VARCHAR(255) NOT NULL,
                         country VARCHAR(255) NOT NULL,
                         notes TEXT NOT NULL DEFAULT '',

                         complete BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX targets_mission_id_idx ON targets (mission_id);

COMMENT ON TABLE targets IS 'Stores individual targets that are part of a mission.';
COMMENT ON COLUMN targets.mission_id IS 'The mission this target belongs to.';
COMMENT ON COLUMN targets.notes IS 'Notes collected by the spy cat about this target.';
COMMENT ON COLUMN targets.complete IS 'True if the spy cat has completed work on this target.';